# Generated by Django 3.0.3 on 2020-04-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('how_heard', models.CharField(max_length=100)),
                ('where', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
    ]
