# Generated by Django 3.0.3 on 2020-04-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='opinion',
            new_name='note',
        ),
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(verbose_name='watch date'),
        ),
    ]
